# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.today)),
                ('cantidad_ingreso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('cantidad_pedido', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_pedido', models.PositiveIntegerField(blank=True, null=True)),
                ('estado_pedido', models.CharField(default='Pendiente', max_length=20)),
                ('id_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Combustible')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso_combustible',
            name='id_pedido_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pedido_combustible'),
        ),
    ]
