# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_cliente', models.CharField(max_length=50, unique=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(blank=True, max_length=50)),
                ('direccion_cliente', models.CharField(blank=True, max_length=50)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50)),
                ('correo_cliente', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.datetime.today)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('domicilio_obra', models.CharField(blank=True, max_length=100)),
                ('estado_venta', models.CharField(default='Pendiente', max_length=100)),
                ('tipo_venta', models.CharField(blank=True, max_length=100)),
                ('total_venta', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('precio_producto', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta')),
            ],
        ),
    ]
